// Flight routes mapping
export const DIRECT_ROUTES: Record<string, string[]> = {
  // Major hubs
  'DEN': ['SLC', 'JAC', 'HDN', 'EGE', 'ASE', 'GUC', 'MTJ', 'BZN', 'SEA', 'LAX', 'SFO', 'ORD', 'DFW'],
  'SLC': ['JAC', 'DEN', 'LAX', 'SEA', 'PDX', 'BZN', 'FCA', 'SFO'],
  'SEA': ['DEN', 'SLC', 'PDX', 'BLI', 'GEG', 'FCA', 'BZN', 'SFO', 'LAX'],
  
  // Regional airports with limited connections
  'JAC': ['DEN', 'SLC', 'LAX', 'SFO'],
  'HDN': ['DEN', 'ORD', 'LAX'],
  'EGE': ['DEN', 'ORD', 'LAX'],
  'ASE': ['DEN', 'ORD', 'LAX'],
  'BZN': ['DEN', 'SLC', 'SEA', 'MSP'],
  'FCA': ['SEA', 'SLC', 'MSP'],
  
  // Major origin cities
  'STL': ['DEN', 'ORD', 'DFW', 'LAX'],
  'MSP': ['DEN', 'SLC', 'SEA', 'ORD', 'BZN', 'FCA'],
  'SFO': ['DEN', 'SLC', 'SEA', 'JAC', 'LAX'],
  'BOS': ['DEN', 'ORD', 'JFK', 'LAX'],
  'AUS': ['DEN', 'DFW', 'LAX'],
  'DFW': ['DEN', 'SLC', 'LAX'],
  'ORD': ['DEN', 'SLC', 'JAC', 'HDN', 'EGE', 'ASE'],
  'LAX': ['DEN', 'SLC', 'SEA', 'JAC', 'HDN', 'EGE', 'ASE'],
};

// Ski pass to resort mapping
export const PASS_RESORTS: Record<string, string[]> = {
  'epic': [
    'beavercreek',
    'breck',
    'copper',
    'crested-butte',
    'heavenly',
    'homewood',
    'keystone',
    'kirkwood',
    'loon',
    'loveland',
    'mtbachelor',
    'mthood',
    'northstar',
    'okemo',
    'parkcity',
    'snowshoe',
    'stowe',
    'vail',
    'whistler-blackcomb',
    'winter-park',
  ],
  'ikon': [
    'alpine-meadows',
    'alta',
    'arapahoe-basin',
    'aspen-highlands',
    'aspen-mountain',
    'big-bear',
    'big-sky',
    'brighton',
    'buttermilk',
    'deer-valley',
    'grand-targhee',
    'jackson-hole',
    'killington',
    'mammoth-lakes',
    'palisades',
    'schweitzer',
    'snowbasin',
    'snowbird',
    'snowmass',
    'solitude',
    'steamboat',
    'sugarbush',
    'sugarloaf',
    'sunvalley',
    'taos',
    'telluride',
    'tremblant',
  ],
  'indy': [
    'bogusbasin',
    'monarch',
    'red-mountain',
    'whitefish',
  ],
  'mountain-collective': [
    'alta',
    'aspen-highlands',
    'aspen-mountain',
    'big-sky',
    'grand-targhee',
    'jackson-hole',
    'snowbasin',
    'snowbird',
    'sugarloaf',
    'sunvalley',
    'taos',
  ],
}; 